### ISSUE TITLE
LocalHost Error

### ISSUE THREAD

**Issue by mrghubba** [BuidlGuidl/abi.ninja#1]
I tried using the site with **LocalHost 8545**. But I have been getting this error message: **"Wrong Network
You have selected and you need to be on Mainnet."**

So does this Dapp work with **Ganache**?

Or is LocalHost referring to something else? 
Thanks

**Comment by technophile-04** [comment]
> But I have been getting this error message: "Wrong Network You have selected and you need to be on Mainnet."

This is should be fixed in #32, as long as the chainId is `31337` and chain is running on locahost:8545 it should work 🙌

Closing this but please feel free to create new issue if you encounter it again, thanks !
