### ISSUE TITLE
bug: modals opening really slow

### ISSUE THREAD

**Issue by portdeveloper** [BuidlGuidl/abi.ninja#105]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

https://github.com/BuidlGuidl/abi.ninja/assets/108868128/bb9f416d-36ec-43ac-a809-b5b4b2f14e0c

### Expected Behavior

It should open faster 

### Steps To Reproduce

1. Go to abi.ninja, open Gitcoin contract or any other contract
2. Connect your wallet
3. Click on View QR Code
<img width="262" alt="image" src="https://github.com/BuidlGuidl/abi.ninja/assets/108868128/86694cae-416e-4cca-8840-3de579bdb470">

**Comment by carletex** [comment]
Works fine & fast for me! Some weird rendering happening in your browser. Have you tried with a diff one?

**Comment by portdeveloper** [comment]
weirdly it opens very slow on two of my computers with 4 different browsers(all flavors of chrome)

closing the issue right now
