### ISSUE TITLE
Let the user config which chains to show in the network dropdown

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#118]
With #109 we let the users search for other chains (not included into the popular list), and they can add them to the network dropdown.

After some use, a "hardcore user" may end with a pretty big network dropdown if we don't let them delete networks.

Not sure about the best UX for it:
- Have the same modal with chain cards, but your current dropdown networks appear at top with a selected check, and you can check/uncheck cards to customize your dropdown. Search feature would remain the same I guess, searching on all networks.
We might just let the user tweak the "Other chains" and not the popular chains with good icons we have by default, if not the list of cards on top may be too big.

- Transform modal to a "double table UI", having at the left table all networks except your selection, and on the right table your selection of networks. Having the ability to add from left to right, and to delete networks from your selection (which will appear in the left table now).
Both could have search, but mainly on the left table.

- Maybe we could even have an X icon on the networks you added directly in the dropdown menu, if you click the X they get deleted from localstorage. Users may missclick when trying to select the network?

Who knows how many users will be adding networks, maybe we could just wait and see if this issue is really needed.

**Comment by Pabl0cks** [comment]
> I think that is a simpler approach that we could take for now. Easy to implement and to understand. lmk what you think

Yeah I think it may be the simpler! We can try it and see how the UX feels. We should let the user delete custom chains and not popular chains? (basically all with abi ninja logo?)

**Comment by portdeveloper** [comment]
> > I think that is a simpler approach that we could take for now. Easy to implement and to understand. lmk what you think
> 
> Yeah I think it may be the simpler! We can try it and see how the UX feels. We should let the user delete custom chains and not popular chains? (basically all with abi ninja logo?)

https://github.com/BuidlGuidl/abi.ninja/assets/108868128/ae528366-248f-4bc2-813b-c15aff89e499

How does this look? I have added just a simple X on the right of added other chains.

**Comment by Pabl0cks** [comment]
> How does this look? I have added just a simple X on the right of added other chains.

I like it, and I feel it will be easy to understand by the user. They will just see the X on the chains they previously added, so regular users won't see anything new, and the users adding networks will probably understand why only these chains are deleteable.

Maybe would be a good idea to have some different hover effect if you hover over the X? To make sure you don't select when you wanted to delete and vice-versa

**Comment by portdeveloper** [comment]
> Maybe would be a good idea to have some different hover effect if you hover over the X? To make sure you don't select when you wanted to delete and vice-versa

Currently only the cursor changes. I have explored a few options but they are a bit too complex for what they provide since this all happens inside the option

**Comment by Pabl0cks** [comment]
> Currently only the cursor changes. I have explored a few options but they are a bit too complex for what they provide since this all happens inside the option

Ok! Probably is just enough with the cursor 👌

**Comment by portdeveloper** [comment]
Should we close this?

**Comment by Pabl0cks** [comment]
> Should we close this?

Yeah! Closing, merged in #127
