### ISSUE TITLE
`IntegerInput` tooltip is not readable in dark mode

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#122]
When you hover on the asterisk, the tooltip that explains the wei conversion "Multiply by ..." needs some tweaks to make it more readable in dark mode.

![photo_2024-06-25_20-17-39](https://github.com/BuidlGuidl/abi.ninja/assets/55535804/c56b9f7a-9618-4613-8292-0014d2372d71)

**Comment by portdeveloper** [comment]
Closing, fixed in the PR above!
