### ISSUE TITLE
Pretty transaction result on contract page

### ISSUE THREAD

**Issue by technophile-04** [BuidlGuidl/abi.ninja#125]
### Description :
 
We merged this in SE-2  https://github.com/scaffold-eth/scaffold-eth-2/pull/853, maybe we should port it to Abi ninja too

**Comment by portdeveloper** [comment]
How do you think this looks?
https://github.com/BuidlGuidl/abi.ninja/assets/108868128/507d6d2a-d718-4352-8f4c-c417ee8de94d

the code is on branch feat/better-tx-result

I have used byte's changes + changed the color + changed one line of code

**Comment by technophile-04** [comment]
Completed at #130
