### ISSUE TITLE
bug: base goerli deprecated, add base sepolia testnet to networks

### ISSUE THREAD

**Issue by tantodefi** [BuidlGuidl/abi.ninja#126]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

**Comment by tantodefi** [comment]
kinda addressed by #120 by port but only partially

**Comment by technophile-04** [comment]
Thanks @tantodefi, it should be fixed by #121 

![image](https://github.com/BuidlGuidl/abi.ninja/assets/80153681/f8d590de-9d84-484e-8a13-eb28e6d58d00)


https://abi.ninja/0x8806fc80A0274Eda6a45E2944f6bB6E6Bb635831/84532?methods=userGreetingCounter
