### ISSUE TITLE
upgrade gulltoppr

### ISSUE THREAD

**Issue by portdeveloper** [BuidlGuidl/abi.ninja#133]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

Now our heimdall backend(gulltoppr) can work with any chain. 

https://github.com/portdeveloper/gulltoppr

It accepts a rpc url instead of a chain id. 

I think we should update the logic + endpoint it given that we have more chains + custom chains now.

https://heimdall-api.fly.dev/[CONTRACT_ADDRESS]?rpc_url=[RPC_URL_WITHOUT_HTTPS://]

Example usage

https://heimdall-api.fly.dev/0x759c0e9d7858566df8ab751026bedce462ff42df?rpc_url=rpc.ankr.com/eth_sepolia

**Comment by carletex** [comment]
Are we using the admin@bg fly instance?? If so, I can give you the user/pass to do this.
