### ISSUE TITLE
e2e actions test fails on forked repo PR

### ISSUE THREAD

**Issue by technophile-04** [BuidlGuidl/abi.ninja#144]
### Description 

It seem when you create an PR from a forked repo the test fails since I think they are not able to access the environment from our repo.

**Comment by portdeveloper** [comment]
`name: E2E on Chrome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/nextjs
          browser: chrome
          start: yarn dev
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_HEIMDALL_URL: ${{ secrets.HEIMDALL_URL }}
          CYPRESS_HEIMDALL_URL: ${{ secrets.HEIMDALL_URL }}
        if: github.event.pull_request.head.repo.full_name == github.repository

      - name: Cypress run (fork PR)
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/nextjs
          browser: chrome
          start: yarn dev
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_HEIMDALL_URL: "https://dummy-heimdall-url.example.com"
          CYPRESS_HEIMDALL_URL: "https://dummy-heimdall-url.example.com"
        if: github.event.pull_request.head.repo.full_name != github.repository`
        
We could probably do it like this but if we make it like this then we should as well remove the use of secrets

**Comment by technophile-04** [comment]
Fixed at #152
