### ISSUE TITLE
Update the unfurl to say EVM chains instead of Ethereum

### ISSUE THREAD

**Issue by portdeveloper** [BuidlGuidl/abi.ninja#148]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

![image](https://github.com/user-attachments/assets/c4f75be8-92d8-4f9f-a691-2ec80b1ee99b)

### Expected Behavior

It should say on any EVM chain or something

### Steps To Reproduce

https://metatags.io/?url=https%3A%2F%2Fabi.ninja

**Comment by technophile-04** [comment]
Ohh yeah maybe "Interact with any contract on any EVM chain"? maybe you can create a PR and we iterate their? Also cc @Pabl0cks if he has better sentence/line 🙌

**Comment by carletex** [comment]
> "Interact with any contract on any EVM chain"

An alternative to avoid the double "any":

"Interact with smart(optional :D) contracts on any EVM chain"

**Comment by andrealbiac** [comment]
Dropping it here too just in case!

![Unfurl-abi-2](https://github.com/user-attachments/assets/93316faa-3457-4cc6-a525-f5cbd1da091b)
