### ISSUE TITLE
bug: Interactions with USDC proxy contract in mainnet

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#156]
In #155 we are fixing open zeppelin proxy detection, but we then have some issues on the interactions with these kind of contracts.

### How to reproduce

We'll reproduce it trying to read the USDC balance on mainnet (CA: `0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48`) for Vitalik's address (vitalik.eth - `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045`)

In [etherscan read as a proxy](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readProxyContract) you can read the balance of an account nicely (0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045) but not in [abi ninja](https://abi-ninja-v2-git-fix-open-zeppelin-impl-detection-buidlguidldao.vercel.app/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/1?methods=balanceOf)

It seems like if we are querying directly the implementation address, like [etherscan does here](https://etherscan.io/address/0x43506849d7c04f9138d1a2050bbf3a0c054402dd#readContract)

Also if you open [USDC mainnet in abi ninja](https://abi-ninja-v2-git-fix-open-zeppelin-impl-detection-buidlguidldao.vercel.app/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/1) and select a method, the URL reloads to the [implementation address](https://abi-ninja-v2-git-fix-open-zeppelin-impl-detection-buidlguidldao.vercel.app/0x43506849d7c04f9138d1a2050bbf3a0c054402dd/1?methods=balanceOf)

**Comment by portdeveloper** [comment]
Fixed in #155 !
