### ISSUE TITLE
chore: NetworksDropdown's display (internal state) and external state could be different

### ISSUE THREAD

**Issue by lukaw3d** [BuidlGuidl/abi.ninja#158]
NetworksDropdown's internal state and display initialize with `initialGroupedOptions.mainnet.options[0]`.
Parent component and fetching initializes with `mainnet.id.toString()`.

These will be out of sync if a repo fork changes which chains are displayed in a dropdown.

https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/pages/index.tsx#L175

https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/pages/index.tsx#L30

https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/components/NetworksDropdown/NetworksDropdown.tsx#L25

https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/components/NetworksDropdown/NetworksDropdown.tsx#L146

Possibly also:
- https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/services/store/store.ts#L68
- https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/services/store/store.ts#L35
- https://github.com/BuidlGuidl/abi.ninja/blob/1cf1f8d5bf3cb368da7ad4f05543cd36d2add752/packages/nextjs/utils/scaffold-eth/contractNames.ts#L5

**Comment by portdeveloper** [comment]
Closing!
