### ISSUE TITLE
feature request: allow wallet connection from localhost

### ISSUE THREAD

**Issue by jennypollack** [BuidlGuidl/abi.ninja#16]
specifically connecting to anvil / foundry would be nice, similar to https://github.com/blacksmith-eth/blacksmith

**Comment by technophile-04** [comment]
Hey thanks for raising the issue, it should be fixed in #32 and should work with anvil / hardhat or any local chain which uses chainId 31337 & starts on localhost:8545 

Closing this but please feel to create new issue if it doesn't work properly, thanks!
