### ISSUE TITLE
bug: contract address input behavior on localhost

### ISSUE THREAD

**Issue by portdeveloper** [BuidlGuidl/abi.ninja#160]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

https://github.com/user-attachments/assets/f1148d7b-4f33-409d-80ac-5d3b70356e64

### Expected Behavior

it should let the user type/paste in an address

### Steps To Reproduce

1. go to https://abi.ninja/
2. try to select localhost as chain

**Comment by technophile-04** [comment]
Completed at #161
