### ISSUE TITLE
Contract UI initial migration

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#23]
Dividing Contract UI in two issues, could be tackled together also. In the initial migration we can:

- [ ] Load methods and info from the contract in the left and right columns.
- [ ] Base design and responsive
- [ ] Page metadata

Methods interaction logic in #24

**Comment by technophile-04** [comment]
Planning to make a PR with initial rendering of contractUI when user paste in verified address or input manual abi

**Comment by technophile-04** [comment]
Ohh Pablo just told me that Port has already a branch just create PR out of that branch #31

**Comment by carletex** [comment]
Oh, let's see if we can join them!

Sorry this happened. To avoid this, let's assign issues (or notify here) if people are working on them.

**Comment by Pabl0cks** [comment]
Sorry I could have assigned Port when he told me about his branch, will try it doesn't happen again 🙌

**Comment by Pabl0cks** [comment]
Good job everyone!! 🙌 

Merged in #31
