### ISSUE TITLE
Create a thumbnail to replace default SE-2 one

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#29]
We can ask Andrea to create one, didn't find any on v1

**Comment by carletex** [comment]
If you mean the share/unfurl thumbnail, we are using this one on v1:

https://abi.ninja/logo.png

**Comment by Pabl0cks** [comment]
Yeah I meant that, don't know why I thought there wasn't any 😅 Pushed to #21  🙌

Thanks @carletex !!

**Comment by technophile-04** [comment]
Was fixed by Pablo at [003a7e6](https://github.com/BuidlGuidl/abi.ninja/pull/21/commits/003a7e618d42b6f24816f9c86efb845cb89c18df) 🙌, closing it
