### ISSUE TITLE
Small title on input fields with field type and variable name

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#39]
Right now we have it on the placeholder, which works, but after you edit it, you lose the placeholder reference. 

I think it would be nice to have it back, not sure about the best solution. We could replicate it in a small title like in v1, or show the title only when placeholder is not showing, or show a tooltip when you hover the field that has data on it... (or any other creative solution we can think 🙃)

**Comment by technophile-04** [comment]
Completed in #44
