### ISSUE TITLE
ContractDetailPage - In resolutions between 640px and 800px the footer loads in the wrong place

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/abi.ninja#42]
Could not reproduce the original error, but found some visual improvements to do, that maybe some of them originated the original bug in some edge case (it happened to me while dual window on laptop with a portable screen):

- Show hamburger menu only when sidebar menu is hidden
- Show X icon only when sidebar is loaded manually (from hamburger)
- Fix X icon position on mobile sidebar menu
- Show always Abi ninja logo in header

Could not reproduce this:

Screenshot =>

![image](https://github.com/BuidlGuidl/abi.ninja/assets/55535804/2d727813-1e8a-4fa3-9847-e98692d0e882)

**Comment by Pabl0cks** [comment]
It's not happening to me right now, but I'll fix in the next PR some strange behaviours on small resolutions from sidebar menu

**Comment by technophile-04** [comment]
Completed in #44
