### ISSUE TITLE
overloaded functions

### ISSUE THREAD

**Issue by austintgriffith** [BuidlGuidl/abi.ninja#66]
<img width="837" alt="image" src="https://github.com/BuidlGuidl/abi.ninja/assets/2653167/1bf646cf-a330-4e8b-88cc-889c25936b60">

it probably needs to handle if a contract has the same function name with different parameters 

I think that's what is going on here: https://abi.ninja/0x00000000fc1237824fb747abde0ff18990e59b7e/10?methods=keysOf

**Comment by technophile-04** [comment]
Completed at #70
