### ISSUE TITLE
ABI Fails to load when pointing at ERC1967Proxy Contracts

### ISSUE THREAD

**Issue by 0xTranqui** [BuidlGuidl/abi.ninja#8]
Finally took the time to dig into this! Amazing open source resource. I have a specific use case I was hoping to fork this for and think I just found a bug (not necessarily a bug, but something missing).

Issue:
- When trying to load the abi for the [ZoraNFTCreatorProxy](https://etherscan.io/address/0xF74B146ce44CC162b601deC3BE331784DB111DC1) (nft factory contract), the contract interactions + abi fail to load.
- When I instead load the abi for the [ZoraNFTCreatorV1](https://etherscan.io/address/0x0DFF6D464fEA23A8A4E0CD6fe94f44B51EF0D96c) contract (the underlying abi that the Zora Proxy points to), it works perfectly :)

Fix:
- Not exactly sure how to implement this myself, but would be amazing if ERC1967Proxy (and other proxy types) support would be added. Proxy infra like this is really common these days and feels like it would make this tool even more helpful.

**Comment by Ifechukwudaniel** [comment]
Is anyone planning on fixing this
