### ISSUE TITLE
Support for custom EVM networks

### ISSUE THREAD

**Issue by dericklau3** [BuidlGuidl/abi.ninja#97]
### Is there an existing issue for this?

- [ ] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

The current supported mainnet and testnet are limited.

### Expected Behavior

Go to support more EVM-compatible chains.

### Steps To Reproduce

None

### Anything else?

None

**Comment by technophile-04** [comment]
Completed at #129
