### ISSUE TITLE
Update the footer logo in text line

### ISSUE THREAD

**Issue by technophile-04** [BuidlGuidl/abi.ninja#99]
### Description : 

Old : 
![Screenshot 2024-05-09 at 11 31 16 PM](https://github.com/BuidlGuidl/abi.ninja/assets/80153681/add584fd-3292-4126-b8a9-400222269808)

New: 
![Screenshot 2024-05-09 at 11 33 17 PM](https://github.com/BuidlGuidl/abi.ninja/assets/80153681/af519d68-1185-4aca-a6f3-563ae16c70a2)

 I think the castle is the new logo, maybe @andrealbiac can share the new logo ?

**Comment by andrealbiac** [comment]
Yes here it is! I exported it as png like a favicon, let me know if it should be different size or svg:

![favicon-bg](https://github.com/BuidlGuidl/abi.ninja/assets/137904915/0d5343a5-5c23-4899-b0b2-a9dd44893874)

**Comment by technophile-04** [comment]
Thanks Andrea !! Closing this as completed in #100
